name: Getting Data

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setting Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Modules
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
          pip install pandas
          pip install urllib3

      - name: Running Script
        run: |
          python sekolah.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
